
server:
  port: 8080
  
spring:

#------keycloak server properties-------#

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/trinitybankdev/protocol/openid-connect/certs
      
      
#-------MySQl database properties-------#

  datasource:
    url: jdbc:mysql://localhost:3306/trinitybankkeycloak
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        formate-sql: true  